#!/usr/bin/env bash

#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 28

#commands to launch
cd ${HOME}/Bureau/tp2/Lab2

export OMP_PROC_BIND=true
OMP_NUM_THREADS=1  ./test
OMP_NUM_THREADS=2	 ./test
OMP_NUM_THREADS=4  ./test
OMP_NUM_THREADS=8  ./test
OMP_NUM_THREADS=10 ./test
OMP_NUM_THREADS=12 ./test
OMP_NUM_THREADS=16 ./test
OMP_NUM_THREADS=28 ./test
